[project]
name = "gpacalc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "grimmjowESP6", email = "mail2arshad113@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
    "flask>=3.0.3",
    "gunicorn>=23.0.0",
]

[project.scripts]
gpacalc = "gpacalc:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
